<x-app-layout>
    <x-slot name="header"><div><p class="text-lg font-black text-slate-950 dark:text-white">Auditoría</p><p class="text-xs text-slate-500">Trazabilidad del sistema</p></div></x-slot>
    <x-page-header title="Registro de auditoría" subtitle="Consulta quién creó, actualizó o eliminó información sensible." />
    <form method="GET" class="panel mb-5 grid gap-3 p-4 sm:grid-cols-[1fr_180px_auto]"><input type="search" name="q" value="{{ request('q') }}" class="form-input" placeholder="Usuario, entidad o identificador"><select name="event" class="form-input"><option value="">Todos los eventos</option><option value="created" @selected(request('event') === 'created')>Creación</option><option value="updated" @selected(request('event') === 'updated')>Actualización</option><option value="deleted" @selected(request('event') === 'deleted')>Eliminación</option></select><button class="btn-secondary">Filtrar</button></form>
    <div class="table-shell">
        @if ($logs->isEmpty())<x-empty-state title="Sin eventos" message="Las operaciones auditadas aparecerán aquí." />
        @else<div class="overflow-x-auto"><table class="data-table"><thead><tr><th>Fecha</th><th>Usuario</th><th>Evento</th><th>Entidad</th><th>IP</th><th>Cambios</th></tr></thead><tbody>@foreach ($logs as $log)<tr><td>{{ $log->created_at->format('d/m/Y h:i:s A') }}</td><td><p class="font-bold">{{ $log->user?->name ?: 'Sistema' }}</p><p class="mt-1 text-xs text-slate-500">{{ $log->user?->email }}</p></td><td><x-status-badge :status="$log->event" /></td><td>{{ $log->subject_name }}</td><td>{{ $log->ip_address ?: '—' }}</td><td><details class="max-w-lg"><summary class="cursor-pointer font-bold text-blue-600">Ver detalle</summary><pre class="mt-3 max-h-64 overflow-auto rounded-lg bg-slate-950 p-3 text-xs text-slate-200">{{ json_encode(['antes' => $log->old_values, 'después' => $log->new_values], JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE) }}</pre></details></td></tr>@endforeach</tbody></table></div><div class="border-t border-slate-200 px-5 py-4 dark:border-slate-800">{{ $logs->links() }}</div>@endif
    </div>
</x-app-layout>
